### ISSUE TITLE
РК3

### ISSUE THREAD

**Issue by iketari** [eugene195/tp_2014_09_java#27]
- Sync должен что-то делать. Интерфейс модели должен быть стандартизирован.
- Удалить лишние *.css и *.map.css

**Comment by streambuf** [comment]
Здравствуйте. Мы всё исправили. Посмотрите пожалуйста.
sync: https://github.com/eugene195/tp_2014_09_java/blob/master/public_html/js/api/sync.js
Может быть общим для всех моделей.

Модель пользователя: https://github.com/eugene195/tp_2014_09_java/blob/master/public_html/js/models/user.js

**Comment by iketari** [comment]
Молодцы. Похоже, что с sync разобрались. Круто, что есть удаленный сервак для разработки. Только не работает что-то. =)
