### ISSUE TITLE
void executeFor(Runnable abonent);

### ISSUE THREAD

**Issue by vitalii-kaplan** [eugene195/tp_2014_09_java#31]
MessageSystem не должна знать о том, что она исполняет сообщения для Runnable.
Сообщения могут быть и не для Runnable.
По задумке сообщения можно отправить всем у кого есть Address.
Сделайте интерфейс Abonent, у которого есть метод getAdress() и все кому доставляете сообщения implements Abonent.

Это сделает систему гибче в том плане, что в одном потоке можно будет обрабатывать сообщения на несколько абонентов, если это "легкие" абоненты. Например объекты пользователей или момбов могут быть абонентами, но "жить" они будут в потоке механики.

**Comment by xammi** [comment]
Действительно, с Abonent система стала проще и гибче
